services:
  - type: web
    name: bingoshop-bot
    runtime: python
    plan: free
    buildCommand: cd bingoshop_bot && pip install -r requirements.txt
    startCommand: cd bingoshop_bot && python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false